name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Get submodules
      run: git submodule update --init --recursive
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile robot code
      run: ./gradlew build

  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Get submodules
        run: git submodule update --init --recursive
      - name: Run spotless linter
        run: ./gradlew spotlessCheck